[project]
name = "gigabyte-rag"
version = "0.1.0"
description = "QA AI assistant system that answers spec. about AORUS MASTER 16 AM6H"
readme = "README.md"
authors = [
    { name = "borissu", email = "b11902166@csie.ntu.edu.tw" }
]
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "numpy>=2.5.3",
    "requests>=2.34.2",
    "sentence-transformers>=6.0.1",
    "huggingface-hub",
    "llama-cpp-python",
    "google-genai",
    "nvidia-cuda-runtime-cu12",
    "nvidia-cublas-cu12",
    "nvidia-cusparse-cu12",
]

# ==========================================
# 告訴 uv 這只是一個應用程式專案，不要嘗試打包它
# ==========================================
[tool.uv]
package = false

# ==========================================
# 告訴 uv 去哪裡下載 CUDA 版本的 llama-cpp-python
# ==========================================
[[tool.uv.index]]
name = "llama-cpp-python-cu124"
url = "https://abetlen.github.io/llama-cpp-python/whl/cu124"
explicit = true 

[tool.uv.sources]
llama-cpp-python = { index = "llama-cpp-python-cu124" }